app_name: "Rails Tutorial App"
admin_email: "hoangvip3333@gmail.com"
default_locale: "en"
name: "Sample App"

i18n:
  default_locale: :en
  available_locales:
    - :en
    - :vi

digits:
  digit_6: 6

page_10: 10

email:
  from_address: "noreply@example.com"
