defaults: &defaults
  app_name: "Rails Tutorial App"
  admin_email: "hoangvip3333@gmail.com"
  default_locale: "en"
  time:
    formats:
      date_of_birth: "%B %d, %Y"
  i18n:
    default_locale: :en
    available_locales:
      - :en
      - :vi

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
